include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    depend_on_referenced_packages: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    unawaited_futures: true
    use_super_parameters: true
